/**
 * Internal ID and composite key generation utilities.
 * Note: Real logistics tracking IDs (e.g., India Post Speed Post consignment numbers)
 * are generated by the backend logistics integration upon dispatch, not on the client.
 */

export const ids = {
  /**
   * Generates a readable internal order ID for client state and proforma invoicing.
   * Format: JSS-YYYY-XXXXX (e.g., JSS-2026-K7M9P)
   */
  generateOrderId() {
    const year = new Date().getFullYear();
    const chars = '23456789ABCDEFGHJKLMNPQRSTUVWXYZ'; // exclude easily confused chars like 0/O, 1/I
    let suffix = '';
    for (let i = 0; i < 5; i++) {
      suffix += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return `JSS-${year}-${suffix}`;
  },

  /**
   * Unique composite key for cart items based on product ID and format/binding variant.
   */
  getCartItemKey(productId, variant = 'Paperback') {
    return `${productId}_${String(variant).trim().toLowerCase()}`;
  }
};

export default ids;
